# Generated by Django 4.2.4 on 2023-09-03 11:48

from django.db import migrations, models
import offers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('off_percent', models.PositiveIntegerField()),
                ('start_date', models.DateField(validators=[offers.models.validate_expiry_date])),
                ('end_date', models.DateField()),
            ],
        ),
    ]
