# Generated by Django 4.2.4 on 2023-09-26 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='off_percent',
            new_name='coupon_price',
        ),
    ]
