# Generated by Django 4.2.4 on 2023-09-26 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_rename_off_percent_coupon_coupon_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='coupon_price',
            new_name='off_percent',
        ),
    ]
