# Generated by Django 4.2.4 on 2023-09-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='color_code',
            field=models.CharField(default='', max_length=10),
        ),
    ]
