# Generated by Django 4.2.4 on 2023-09-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_product_price_remove_product_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='photos/categories'),
        ),
    ]
