# Generated by Django 4.2.4 on 2023-09-21 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_productimage_product_productimage_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='images',
        ),
    ]
