# Generated by Django 4.2.4 on 2023-09-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_payment_payment_method_delete_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_total',
            field=models.FloatField(default=500000),
            preserve_default=False,
        ),
    ]
