# Generated by Django 4.2.4 on 2023-10-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
